language: php
php:
- "7.2"
- "7.3"
before_script:
- composer selfupdate

install:
- composer self-update
- composer install

cache:
  directories:
  - $HOME/.composer/cache

script:
- vendor/bin/phpunit

notifications:
  email:
    on_success: always
    on_failure: always