language: php
php:
- "7.2"
- "7.3"
services:
- mysql

before_script:
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
- pear install pear/PHP_CodeSniffer
- phpenv rehash

install:
- composer self-update
- composer install

cache:
  directories:
  - $HOME/.composer/cache

script:
- vendor/bin/phpunit --coverage-text
- phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers

notifications:
  email:
    on_success: always
    on_failure: always